language: php

git:
  depth: 1

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.6
      env: LARAVEL='5.1.*'
    - php: 5.6
      env: LARAVEL='5.2.*'
    - php: 5.6
      env: LARAVEL='5.3.*'
    - php: 5.6
      env: LARAVEL='5.4.*'
    - php: 7.0
      env: LARAVEL='5.1.*'
    - php: 7.0
      env: LARAVEL='5.2.*'
    - php: 7.0
      env: LARAVEL='5.3.*'
    - php: 7.0
      env: LARAVEL='5.4.*'
    - php: 7.0
      env: LARAVEL='5.5.*'
    - php: 7.1
      env: LARAVEL='5.1.*'
    - php: 7.1
      env: LARAVEL='5.2.*'
    - php: 7.1
      env: LARAVEL='5.3.*'
    - php: 7.1
      env: LARAVEL='5.4.*'
    - php: 7.1
      env: LARAVEL='5.5.*'
    - php: 7.1
      env: LARAVEL='5.6.*'
    - php: 7.1
      env: LARAVEL='5.7.*'
    - php: 7.1
      env: LARAVEL='5.8.*'
    - php: 7.2
      env: LARAVEL='5.1.*'
    - php: 7.2
      env: LARAVEL='5.2.*'
    - php: 7.2
      env: LARAVEL='5.3.*'
    - php: 7.2
      env: LARAVEL='5.4.*'
    - php: 7.2
      env: LARAVEL='5.5.*'
    - php: 7.2
      env: LARAVEL='5.6.*'
    - php: 7.2
      env: LARAVEL='5.7.*'
    - php: 7.2
      env: LARAVEL='5.8.*'
    - php: 7.3
      env: LARAVEL='5.1.*'
    - php: 7.3
      env: LARAVEL='5.2.*'
    - php: 7.3
      env: LARAVEL='5.3.*'
    - php: 7.3
      env: LARAVEL='5.4.*'
    - php: 7.3
      env: LARAVEL='5.5.*'
    - php: 7.3
      env: LARAVEL='5.6.*'
    - php: 7.3
      env: LARAVEL='5.7.*'
    - php: 7.3
      env: LARAVEL='5.8.*'
  fast_finish: true

before_install:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer self-update
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer require "laravel/laravel:${LARAVEL}" --no-interaction --no-update
  - php scripts/mergeRequireDev.php

install:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-dist --no-interaction --no-suggest

script:
  - ./vendor/bin/phpcs ./
  - ./vendor/bin/phpunit
